### ISSUE TITLE
Splitting existing EKS terraform script into modules

### ISSUE THREAD

**Issue by hferentschik** [jenkins-x/jx-cloud-provisioners#1]
What's about splitting the script parts into descriptive modules, either per Jenkins X functional group similar to here https://github.com/jenkins-x/terraform-google-jx/tree/master/jx/modules or by cloud "resource" type, eg _service-account_, _storage_, _secret_.

**Comment by hferentschik** [comment]
I think in an ideal world we should just have _main|output|variables.tf_ in the root level of the terraform directory (together with the README).

**Comment by dgozalo** [comment]
This is a good idea, I'll do this for the EKS scripts.

**Comment by hferentschik** [comment]
> This is a good idea, I'll do this for the EKS scripts.

We probably want to align between the different cloud provider scripts then.
