### ISSUE TITLE
Document the AKS Terraform module in README

### ISSUE THREAD

**Issue by dgozalo** [jenkins-x/jx-cloud-provisioners#19]
# Summary
The created AKS module will need to be documented in its README.md file before we can port it to the official Jenkins X documentation.

Terraform modules documentation usually follow a defined structure. An example can be found in the terraform eks module:

https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/README.md

We'd need the following sections: 

* Assumptions: Any assumption on the current state of the Azure account, permissions etc.
* Usage: how to use this module either by other Terraform scripts or a way to run it directly by Terraform.
* Providers and their versions
* Inputs
* Outputs

The last three can be generated with https://github.com/segmentio/terraform-docs.

# Acceptance Criteria
A README.md with all the required sections.

**Comment by helayoty** [comment]
@dgozalo would you please close this issue? It seems I don't have permission to do so

**Comment by dgozalo** [comment]
Closed by #23
