### ISSUE TITLE
Create Terraform scripts for a basic AKS cluster

### ISSUE THREAD

**Issue by dgozalo** [jenkins-x/jx-cloud-provisioners#21]
# Summary
Create a folder under `terraform` called `aks` and define a Terraform module for creating a simple AKS cluster.

We'll not be considering features like `Long Term Storage`,  `Vault`, `External DNS` or `Cert-manager` in this.

There will be follow up issues to work a feature at a time after this one is complete.

Fine grained permissions will be worked on in a separate issue but should be kept in mind when designing this Terraform module.

Follow up issues are:

#17 
#19 
#16 
#18 
#20 

# Acceptance Criteria

* Terraform module is available to create a simple Azure cluster that can be used to `jx boot` and works with minimum requirements
* Will not cover vault, cert-manager, external DNS, or dealing with long term storage
* Will not need fine grained permissions (covered by another story)

**Comment by dennisnewel** [comment]
updated the acceptance criteria a bit as a sample of exclusion statements. @dgozalo do you have a link to "minimum requirements"? it'd be good to reference what those are so there's no misunderstanding of what should be covered in this initial issue

**Comment by helayoty** [comment]
\close

**Comment by helayoty** [comment]
@dgozalo would you please close this issue? It seems I don't have permission to do so

**Comment by dgozalo** [comment]
Closed by #23
